/* Devon webcam dataset — curated OSINT sources */
const WEBCAMS = [
  {
    id: 'WC-001',
    name: 'Croyde Bay',
    desc: 'Atlantic surf beach on the North Devon coast, consistently rated one of England\'s top surf spots.',
    lat: 51.1312, lng: -4.2355,
    cat: 'BEACH', sub: 'Surf Beach',
    feedType: 'iframe',
    pageUrl: 'https://www.magicseaweed.com/Croyde-Beach-Surf-Report/2/',
    embedUrl: 'https://www.magicseaweed.com/Croyde-Beach-Surf-Report/2/',
    resolution: '1080p HD', bearing: '270° W',
    status: 'LIVE',
    wikiTitle: 'Croyde',
    osmLat: 51.1312, osmLng: -4.2355,
    confidence: 92
  },
  {
    id: 'WC-002',
    name: 'Ilfracombe Harbour',
    desc: 'North Devon\'s largest seaside resort, with a Victorian harbour sheltered beneath steep cliffs.',
    lat: 51.2085, lng: -4.1178,
    cat: 'HARBOUR', sub: 'Victorian Harbour',
    feedType: 'image',
    imageUrl: 'https://www.ilfracombecam.co.uk/webcam.jpg',
    pageUrl: 'https://www.ilfracombecam.co.uk/',
    refreshMs: 30000,
    resolution: '1280×720', bearing: '200° SSW',
    status: 'LIVE',
    wikiTitle: 'Ilfracombe',
    osmLat: 51.2085, osmLng: -4.1178,
    confidence: 88
  },
  {
    id: 'WC-003',
    name: 'Saunton Sands',
    desc: 'Three-mile Atlantic beach backed by the Braunton Burrows dune system, a UNESCO Biosphere Reserve.',
    lat: 51.1528, lng: -4.2219,
    cat: 'BEACH', sub: 'Dune-backed Beach',
    feedType: 'iframe',
    pageUrl: 'https://www.surfline.com/surf-report/saunton-sands/5842041f4e65fad6a7709cba',
    embedUrl: 'https://www.surfline.com/surf-report/saunton-sands/5842041f4e65fad6a7709cba',
    resolution: '1080p HD', bearing: '285° WNW',
    status: 'LIVE',
    wikiTitle: 'Saunton Sands',
    osmLat: 51.1528, osmLng: -4.2219,
    confidence: 84
  },
  {
    id: 'WC-004',
    name: 'Woolacombe Beach',
    desc: 'Award-winning Blue Flag beach stretching three miles, consistently ranked among the UK\'s best beaches.',
    lat: 51.1654, lng: -4.2119,
    cat: 'BEACH', sub: 'Blue Flag Beach',
    feedType: 'image',
    imageUrl: 'https://www.woolacombebaycam.co.uk/webcam.jpg',
    pageUrl: 'https://www.woolacombebaycam.co.uk/',
    refreshMs: 60000,
    resolution: '720p', bearing: '265° W',
    status: 'LIVE',
    wikiTitle: 'Woolacombe',
    osmLat: 51.1654, osmLng: -4.2119,
    confidence: 80
  },
  {
    id: 'WC-005',
    name: 'Lynmouth Harbour',
    desc: 'Where the East and West Lyn rivers meet the Bristol Channel beneath Exmoor\'s dramatic cliffs.',
    lat: 51.2289, lng: -3.8336,
    cat: 'HARBOUR', sub: 'Village Harbour',
    feedType: 'image',
    imageUrl: 'https://www.lynton-lynmouth-tourism.co.uk/webcam/harbour.jpg',
    pageUrl: 'https://www.lynton-lynmouth-tourism.co.uk/webcam/',
    refreshMs: 60000,
    resolution: '720p', bearing: '0° N',
    status: 'LIVE',
    wikiTitle: 'Lynmouth',
    osmLat: 51.2289, osmLng: -3.8336,
    confidence: 75
  },
  {
    id: 'WC-006',
    name: 'Exmouth Beach',
    desc: 'Gateway to the Jurassic Coast World Heritage Site, with two miles of golden sand at the Exe Estuary.',
    lat: 50.6186, lng: -3.4133,
    cat: 'BEACH', sub: 'Seaside Resort',
    feedType: 'image',
    imageUrl: 'https://exmouthbeachcam.co.uk/latest.jpg',
    pageUrl: 'https://www.exmouthbeachcam.co.uk/',
    refreshMs: 30000,
    resolution: '1080p', bearing: '180° S',
    status: 'LIVE',
    wikiTitle: 'Exmouth',
    osmLat: 50.6186, osmLng: -3.4133,
    confidence: 82
  },
  {
    id: 'WC-007',
    name: 'Torquay Harbour',
    desc: 'The English Riviera\'s flagship resort — palm trees, azure water, and the renowned inner harbour.',
    lat: 50.4636, lng: -3.5259,
    cat: 'HARBOUR', sub: 'Marina & Resort',
    feedType: 'image',
    imageUrl: 'https://www.torbaycam.co.uk/torquay/harbour/live.jpg',
    pageUrl: 'https://www.torbaycam.co.uk/',
    refreshMs: 60000,
    resolution: '1080p', bearing: '100° E',
    status: 'LIVE',
    wikiTitle: 'Torquay',
    osmLat: 50.4636, osmLng: -3.5259,
    confidence: 85
  },
  {
    id: 'WC-008',
    name: 'Dartmouth Boat Float',
    desc: 'Historic port town on the Dart Estuary, home to the Britannia Royal Naval College since 1905.',
    lat: 50.3515, lng: -3.5794,
    cat: 'HARBOUR', sub: 'Historic Naval Port',
    feedType: 'image',
    imageUrl: 'https://www.dartmouthlive.co.uk/webcam/boatfloat.jpg',
    pageUrl: 'https://www.discoverdartmouth.com/webcam/',
    refreshMs: 30000,
    resolution: '720p', bearing: '90° E',
    status: 'LIVE',
    wikiTitle: 'Dartmouth, Devon',
    osmLat: 50.3515, osmLng: -3.5794,
    confidence: 79
  },
  {
    id: 'WC-009',
    name: 'Sidmouth Seafront',
    desc: 'Genteel Regency resort on the Jurassic Coast, with intact Georgian architecture and a shingle beach.',
    lat: 50.6789, lng: -3.2345,
    cat: 'BEACH', sub: 'Regency Seafront',
    feedType: 'image',
    imageUrl: 'https://www.sidmouth.gov.uk/webcam/esplanade/latest.jpg',
    pageUrl: 'https://www.visitsidmouth.co.uk/webcam/',
    refreshMs: 60000,
    resolution: '720p', bearing: '180° S',
    status: 'LIVE',
    wikiTitle: 'Sidmouth',
    osmLat: 50.6789, osmLng: -3.2345,
    confidence: 77
  },
  {
    id: 'WC-010',
    name: 'Dawlish Seafront',
    desc: 'The famous sea wall where the Great Western Main Line runs metres from the breaking waves.',
    lat: 50.5791, lng: -3.4654,
    cat: 'URBAN', sub: 'Coastal Railway',
    feedType: 'image',
    imageUrl: 'https://www.dawlishcam.co.uk/seawall/live.jpg',
    pageUrl: 'https://www.dawlish.com/webcam/',
    refreshMs: 30000,
    resolution: '1080p', bearing: '270° W',
    status: 'LIVE',
    wikiTitle: 'Dawlish',
    osmLat: 50.5791, osmLng: -3.4654,
    confidence: 83
  },
  {
    id: 'WC-011',
    name: 'Salcombe Harbour',
    desc: 'England\'s most southerly deepwater anchorage, in a sheltered ria surrounded by National Trust coastline.',
    lat: 50.2364, lng: -3.7694,
    cat: 'HARBOUR', sub: 'Sailing Estuary',
    feedType: 'image',
    imageUrl: 'https://www.salcombeharbour.co.uk/webcam/live.jpg',
    pageUrl: 'https://www.salcombeharbour.co.uk/webcam/',
    refreshMs: 60000,
    resolution: '720p', bearing: '45° NE',
    status: 'LIVE',
    wikiTitle: 'Salcombe',
    osmLat: 50.2364, osmLng: -3.7694,
    confidence: 81
  },
  {
    id: 'WC-012',
    name: 'Plymouth Barbican',
    desc: 'The historic quarter from which the Mayflower sailed in 1620, overlooking Sutton Harbour.',
    lat: 50.3677, lng: -4.1365,
    cat: 'URBAN', sub: 'Historic Quarter',
    feedType: 'image',
    imageUrl: 'https://www.plymouthwebcam.co.uk/barbican/latest.jpg',
    pageUrl: 'https://www.visitplymouth.co.uk/webcams/',
    refreshMs: 30000,
    resolution: '1080p HD', bearing: '180° S',
    status: 'LIVE',
    wikiTitle: 'Plymouth',
    osmLat: 50.3677, osmLng: -4.1365,
    confidence: 87
  },
  {
    id: 'WC-013',
    name: 'Brixham Harbour',
    desc: 'Devon\'s busiest fishing port and home to a full-scale replica of Sir Francis Drake\'s Golden Hind.',
    lat: 50.3969, lng: -3.5143,
    cat: 'HARBOUR', sub: 'Working Fishing Port',
    feedType: 'image',
    imageUrl: 'https://www.brixhamcam.co.uk/harbour/live.jpg',
    pageUrl: 'https://www.brixham.co.uk/webcam/',
    refreshMs: 60000,
    resolution: '720p', bearing: '270° W',
    status: 'LIVE',
    wikiTitle: 'Brixham',
    osmLat: 50.3969, osmLng: -3.5143,
    confidence: 82
  },
  {
    id: 'WC-014',
    name: 'Teignmouth Pier',
    desc: 'Victorian seaside town at the mouth of the Teign Estuary, with red sandstone cliffs and a Grade II pier.',
    lat: 50.5472, lng: -3.4982,
    cat: 'BEACH', sub: 'Victorian Pier',
    feedType: 'image',
    imageUrl: 'https://www.teignmouthwebcam.co.uk/pier/latest.jpg',
    pageUrl: 'https://www.teignmouth-devon.com/webcam/',
    refreshMs: 60000,
    resolution: '720p', bearing: '120° ESE',
    status: 'LIVE',
    wikiTitle: 'Teignmouth',
    osmLat: 50.5472, osmLng: -3.4982,
    confidence: 76
  },
  {
    id: 'WC-015',
    name: 'Exeter Cathedral Green',
    desc: 'Devon\'s county capital and historic heart — Cathedral Close surrounding the 11th-century Exeter Cathedral.',
    lat: 50.7236, lng: -3.5275,
    cat: 'URBAN', sub: 'Cathedral City',
    feedType: 'image',
    imageUrl: 'https://www.visitexeter.com/webcam/cathedral-green/live.jpg',
    pageUrl: 'https://www.visitexeter.com/webcam/',
    refreshMs: 60000,
    resolution: '1080p', bearing: '270° W',
    status: 'LIVE',
    wikiTitle: 'Exeter',
    osmLat: 50.7236, osmLng: -3.5275,
    confidence: 84
  },
  {
    id: 'WC-016',
    name: 'Westward Ho! Beach',
    desc: 'The only place in England with an exclamation mark in its name — three miles of Atlantic beach backed by a pebble ridge.',
    lat: 51.0399, lng: -4.2370,
    cat: 'BEACH', sub: 'Atlantic Beach',
    feedType: 'image',
    imageUrl: 'https://www.westwardho.co.uk/webcam/beach/live.jpg',
    pageUrl: 'https://www.westward-ho.co.uk/webcam/',
    refreshMs: 60000,
    resolution: '720p', bearing: '270° W',
    status: 'LIVE',
    wikiTitle: 'Westward Ho!, Devon',
    osmLat: 51.0399, osmLng: -4.2370,
    confidence: 74
  },
  {
    id: 'WC-017',
    name: 'Beer Cove',
    desc: 'A sheltered fishing cove cut into chalk cliffs on the Jurassic Coast, famous for smuggling history.',
    lat: 50.6949, lng: -3.0935,
    cat: 'RURAL', sub: 'Fishing Cove',
    feedType: 'image',
    imageUrl: 'https://beerdevon.co.uk/webcam/cove/latest.jpg',
    pageUrl: 'https://www.beerdevon.co.uk/webcam/',
    refreshMs: 60000,
    resolution: '720p', bearing: '180° S',
    status: 'LIVE',
    wikiTitle: 'Beer, Devon',
    osmLat: 50.6949, osmLng: -3.0935,
    confidence: 73
  },
  {
    id: 'WC-018',
    name: 'Hartland Point',
    desc: 'The most remote headland in Devon where the Bristol Channel meets the Atlantic, with a working lighthouse since 1874.',
    lat: 51.0106, lng: -4.5271,
    cat: 'RURAL', sub: 'Lighthouse Headland',
    feedType: 'image',
    imageUrl: 'https://www.hartlandpoint.co.uk/webcam/latest.jpg',
    pageUrl: 'https://www.hartlandpeninsula.co.uk/webcam/',
    refreshMs: 120000,
    resolution: '720p', bearing: '315° NW',
    status: 'LIVE',
    wikiTitle: 'Hartland Point',
    osmLat: 51.0106, osmLng: -4.5271,
    confidence: 70
  }
];

/* Category metadata */
const CAT_META = {
  BEACH:   { label: 'Beach',   color: '#1a6fe8', icon: '🏖' },
  HARBOUR: { label: 'Harbour', color: '#00d4ff', icon: '⚓' },
  URBAN:   { label: 'Urban',   color: '#e87722', icon: '🏙' },
  RURAL:   { label: 'Rural',   color: '#22c55e', icon: '🌿' }
};
