/* Devon webcam dataset — verified OSINT sources, April 2025
   Feed types:
     youtube  → embedded YouTube live stream (confirmed 24/7)
     link     → external source, not directly embeddable (opens new tab)
*/
const WEBCAMS = [
  {
    id: 'WC-001',
    name: 'Croyde Bay',
    desc: 'Atlantic surf beach on the North Devon coast, consistently rated one of England\'s top surf spots with powerful beach break waves.',
    lat: 51.1312, lng: -4.2355,
    cat: 'BEACH', sub: 'Surf Beach',
    feedType: 'link',
    pageUrl: 'https://www.windy.com/webcams/1334584616',
    sourceLabel: 'Windy.com',
    resolution: 'HD', bearing: '270° W',
    status: 'LIVE',
    wikiTitle: 'Croyde',
    confidence: 90
  },
  {
    id: 'WC-002',
    name: 'Ilfracombe Harbour',
    desc: 'North Devon\'s largest seaside resort, with a Victorian harbour sheltered beneath steep cliffs and the landmark Verity statue by Damien Hirst.',
    lat: 51.2085, lng: -4.1178,
    cat: 'HARBOUR', sub: 'Victorian Harbour',
    feedType: 'link',
    pageUrl: 'https://www.camsecure.co.uk/Camsecure3/ilfracombe_webcam.html',
    sourceLabel: 'Camsecure',
    resolution: 'HD', bearing: '200° SSW',
    status: 'LIVE',
    wikiTitle: 'Ilfracombe',
    confidence: 88
  },
  {
    id: 'WC-003',
    name: 'Saunton Sands',
    desc: 'Three-mile Atlantic beach backed by the Braunton Burrows dune system — a UNESCO Biosphere Reserve and one of England\'s finest surf beaches.',
    lat: 51.1528, lng: -4.2219,
    cat: 'BEACH', sub: 'Dune-backed Beach',
    feedType: 'youtube',
    youtubeId: 'YkPKjA1aLs0',
    pageUrl: 'https://www.youtube.com/watch?v=YkPKjA1aLs0',
    sourceLabel: 'Chalet Saunton · YouTube Live',
    resolution: '1080p HD', bearing: '285° WNW',
    status: 'LIVE',
    wikiTitle: 'Saunton Sands',
    confidence: 96
  },
  {
    id: 'WC-004',
    name: 'Woolacombe Beach',
    desc: 'Award-winning Blue Flag beach stretching three miles, consistently ranked among the UK\'s best beaches with reliable surf and golden sand.',
    lat: 51.1654, lng: -4.2119,
    cat: 'BEACH', sub: 'Blue Flag Beach',
    feedType: 'link',
    pageUrl: 'https://www.windy.com/webcams/1301593463',
    sourceLabel: 'Windy.com',
    resolution: 'HD', bearing: '265° W',
    status: 'LIVE',
    wikiTitle: 'Woolacombe',
    confidence: 85
  },
  {
    id: 'WC-005',
    name: 'Lynmouth Harbour',
    desc: 'Where the East and West Lyn rivers meet the Bristol Channel beneath Exmoor\'s dramatic wooded cliffs, scene of the devastating 1952 flood.',
    lat: 51.2289, lng: -3.8336,
    cat: 'HARBOUR', sub: 'Village Harbour',
    feedType: 'link',
    pageUrl: 'https://www.farsondigitalwatercams.com/locations/lynmouth',
    sourceLabel: 'Farson Digital Watercams',
    resolution: 'HD', bearing: '0° N',
    status: 'LIVE',
    wikiTitle: 'Lynmouth',
    confidence: 82
  },
  {
    id: 'WC-006',
    name: 'Exmouth Seafront',
    desc: 'Gateway to the Jurassic Coast World Heritage Site, with two miles of golden sand at the mouth of the Exe Estuary.',
    lat: 50.6186, lng: -3.4133,
    cat: 'BEACH', sub: 'Seaside Resort',
    feedType: 'link',
    pageUrl: 'https://www.exmouthcam.co.uk/webcam/',
    sourceLabel: 'ExmouthCam',
    resolution: 'HD', bearing: '180° S',
    status: 'LIVE',
    wikiTitle: 'Exmouth',
    confidence: 84
  },
  {
    id: 'WC-007',
    name: 'Torquay Harbour',
    desc: 'The English Riviera\'s flagship resort — palm trees, azure water, and the famous inner harbour that inspired Agatha Christie.',
    lat: 50.4636, lng: -3.5259,
    cat: 'HARBOUR', sub: 'Marina & Resort',
    feedType: 'link',
    pageUrl: 'https://www.camsecure.co.uk/torquay_harbour_webcam.html',
    sourceLabel: 'Camsecure',
    resolution: 'HD', bearing: '100° E',
    status: 'LIVE',
    wikiTitle: 'Torquay',
    confidence: 87
  },
  {
    id: 'WC-008',
    name: 'Dartmouth Embankment',
    desc: 'Historic port town on the Dart Estuary, home to the Britannia Royal Naval College since 1905. 24/7 HD live stream from the Embankment Bistro.',
    lat: 50.3515, lng: -3.5794,
    cat: 'HARBOUR', sub: 'Historic Naval Port',
    feedType: 'youtube',
    youtubeId: '2wAQ3OfqklI',
    pageUrl: 'https://www.youtube.com/watch?v=2wAQ3OfqklI',
    sourceLabel: 'Coast Cams · YouTube Live 4K',
    resolution: '4K UHD', bearing: '90° E',
    status: 'LIVE',
    wikiTitle: 'Dartmouth, Devon',
    confidence: 97
  },
  {
    id: 'WC-009',
    name: 'Sidmouth Esplanade',
    desc: 'Genteel Regency resort on the Jurassic Coast, with intact Georgian architecture, a shingle beach, and a renowned folk festival each August.',
    lat: 50.6789, lng: -3.2345,
    cat: 'BEACH', sub: 'Regency Seafront',
    feedType: 'link',
    pageUrl: 'https://sidmouth.gov.uk/webcams/the-esplanade-webcam/',
    sourceLabel: 'Sidmouth Town Council',
    resolution: 'HD', bearing: '180° S',
    status: 'LIVE',
    wikiTitle: 'Sidmouth',
    confidence: 83
  },
  {
    id: 'WC-010',
    name: 'Dawlish Sea Wall',
    desc: 'The famous sea wall where the Great Western Main Line runs metres from the breaking waves — spectacular in storms. Sea Breeze cam, 24/7 HD.',
    lat: 50.5791, lng: -3.4654,
    cat: 'URBAN', sub: 'Coastal Railway',
    feedType: 'youtube',
    youtubeId: 'dODxHaxdT0w',
    pageUrl: 'https://www.youtube.com/watch?v=dODxHaxdT0w',
    sourceLabel: 'Coast Cams · YouTube Live 4K',
    resolution: '4K UHD', bearing: '270° W',
    status: 'LIVE',
    wikiTitle: 'Dawlish',
    confidence: 97
  },
  {
    id: 'WC-011',
    name: 'Salcombe Estuary',
    desc: 'England\'s most southerly deepwater anchorage, in a sheltered ria of the South Devon AONB, popular with yachtsmen from across Europe.',
    lat: 50.2364, lng: -3.7694,
    cat: 'HARBOUR', sub: 'Sailing Estuary',
    feedType: 'link',
    pageUrl: 'https://www.camsecure.co.uk/salcombe_to_portlemouth_webcam.html',
    sourceLabel: 'Camsecure',
    resolution: 'HD', bearing: '45° NE',
    status: 'LIVE',
    wikiTitle: 'Salcombe',
    confidence: 81
  },
  {
    id: 'WC-012',
    name: 'Plymouth Hoe',
    desc: 'The historic promontory from which Drake played bowls before the Armada, overlooking Plymouth Sound — one of England\'s great natural harbours.',
    lat: 50.3677, lng: -4.1365,
    cat: 'URBAN', sub: 'Historic Waterfront',
    feedType: 'link',
    pageUrl: 'https://westwardshippingnews.com/live-webcam/',
    sourceLabel: 'Westward Shipping News',
    resolution: 'HD', bearing: '180° S',
    status: 'LIVE',
    wikiTitle: 'Plymouth',
    confidence: 85
  },
  {
    id: 'WC-013',
    name: 'Brixham Harbour',
    desc: 'Devon\'s busiest working fishing port, landing more fish by value than any other harbour in England, and home to a replica of Drake\'s Golden Hind.',
    lat: 50.3969, lng: -3.5143,
    cat: 'HARBOUR', sub: 'Working Fishing Port',
    feedType: 'link',
    pageUrl: 'https://www.camsecure.co.uk/Camsecure3/Brixham_Harbour.html',
    sourceLabel: 'Camsecure',
    resolution: 'HD', bearing: '270° W',
    status: 'LIVE',
    wikiTitle: 'Brixham',
    confidence: 84
  },
  {
    id: 'WC-014',
    name: 'Teign Estuary',
    desc: 'The Teign Estuary at Teignmouth — Railcam UK\'s 24/7 panning camera covering the estuary, the harbour, and the GWR branch line.',
    lat: 50.5472, lng: -3.4982,
    cat: 'BEACH', sub: 'Estuary & Railcam',
    feedType: 'youtube',
    youtubeId: 'ug3AO8rn0IE',
    pageUrl: 'https://www.youtube.com/watch?v=ug3AO8rn0IE',
    sourceLabel: 'Railcam UK · YouTube Live',
    resolution: '1080p HD', bearing: '90° E',
    status: 'LIVE',
    wikiTitle: 'Teignmouth',
    confidence: 95
  },
  {
    id: 'WC-015',
    name: 'Dawlish Warren',
    desc: 'A sand spit nature reserve at the mouth of the Exe Estuary, popular holiday park and wading bird hotspot — with its own 24/7 Coast Cams stream.',
    lat: 50.5941, lng: -3.4432,
    cat: 'BEACH', sub: 'Nature Reserve Beach',
    feedType: 'youtube',
    youtubeId: 'iL3NeBl8hHA',
    pageUrl: 'https://www.youtube.com/watch?v=iL3NeBl8hHA',
    sourceLabel: 'Coast Cams · YouTube Live',
    resolution: '1080p HD', bearing: '180° S',
    status: 'LIVE',
    wikiTitle: 'Dawlish Warren',
    confidence: 95
  },
  {
    id: 'WC-016',
    name: 'Westward Ho!',
    desc: 'The only place in England with an exclamation mark in its name — three miles of Atlantic beach backed by a pebble ridge Nature Reserve.',
    lat: 51.0399, lng: -4.2370,
    cat: 'BEACH', sub: 'Atlantic Beach',
    feedType: 'link',
    pageUrl: 'https://www.camsecure.co.uk/WestwardHo1.html',
    sourceLabel: 'Camsecure',
    resolution: 'HD', bearing: '270° W',
    status: 'LIVE',
    wikiTitle: 'Westward Ho!, Devon',
    confidence: 80
  },
  {
    id: 'WC-017',
    name: 'Beer Cove',
    desc: 'A sheltered fishing cove cut into chalk cliffs on the Jurassic Coast, with a long smuggling history and colourful fishing boats hauled up the beach.',
    lat: 50.6949, lng: -3.0935,
    cat: 'RURAL', sub: 'Fishing Cove',
    feedType: 'link',
    pageUrl: 'https://beersailingclub.co.uk/Beer%20Sailing%20Club%20Web%20Cam.html',
    sourceLabel: 'Beer Sailing Club',
    resolution: 'HD', bearing: '180° S',
    status: 'LIVE',
    wikiTitle: 'Beer, Devon',
    confidence: 78
  },
  {
    id: 'WC-018',
    name: 'Hartland Quay',
    desc: 'The most remote headland in Devon where the Bristol Channel meets the Atlantic — dramatic black rock geology and a working lighthouse since 1874.',
    lat: 51.0106, lng: -4.5271,
    cat: 'RURAL', sub: 'Headland & Lighthouse',
    feedType: 'link',
    pageUrl: 'https://hartlandquayhotel.co.uk/live-from-hartland-quay/',
    sourceLabel: 'Hartland Quay Hotel',
    resolution: 'HD', bearing: '315° NW',
    status: 'LIVE',
    wikiTitle: 'Hartland Point',
    confidence: 76
  }
];

const CAT_META = {
  BEACH:   { label: 'Beach',   color: '#1a6fe8', icon: '🏖' },
  HARBOUR: { label: 'Harbour', color: '#00d4ff', icon: '⚓' },
  URBAN:   { label: 'Urban',   color: '#e87722', icon: '🏙' },
  RURAL:   { label: 'Rural',   color: '#22c55e', icon: '🌿' }
};
